# ImgAE-Dx Project Configuration

# Project Metadata
project_name: "ImgAE-Dx"
version: "0.1.0"
experiment_name: "unet_vs_reversed_ae"
wandb_project: "imgae-dx"
log_level: "INFO"

# Data Configuration
data:
  num_normal_samples: 2000
  num_abnormal_samples: 1000
  train_val_split: 0.8
  image_size: 128
  normalize_mean: 0.485
  normalize_std: 0.229
  enable_augmentation: true
  rotation_range: 15
  horizontal_flip: true
  brightness_range: [0.8, 1.2]
  streaming_enabled: true
  memory_limit_gb: 4

# Model Configuration
model:
  input_channels: 1
  input_size: 128
  latent_dim: 512
  unet_features: [64, 128, 256, 512]
  unet_dropout: 0.1
  rae_encoder_features: [64, 128, 256]
  rae_decoder_features: [256, 128, 64]
  rae_skip_connections: false

# Training Configuration
training:
  epochs: 10
  batch_size: 32
  learning_rate: 1e-4
  optimizer: "adam"
  weight_decay: 1e-5
  scheduler: "cosine"
  loss_function: "mse"
  save_every: 5
  checkpoint_dir: "checkpoints"
  patience: 10
  min_delta: 1e-4
  val_split: 0.2
  val_frequency: 1

# Streaming Configuration
streaming:
  memory_limit_gb: 4
  batch_size: 32
  num_workers: 0
  prefetch_factor: 2
  cache_size_mb: 512
  dataset_name: "bachrr/covid-chest-xray"
  dataset_stages: ["images"]
  cleanup_frequency: 100
  gc_threshold: 0.8